import { Token, ArbitrageOpportunity, GasPrice } from '../types'
import { SUPPORTED_DEXS } from './chains'

export const POPULAR_TOKENS: Token[] = [
  {
    address: '0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2', // WETH on Ethereum
    name: 'Wrapped Ether',
    symbol: 'WETH',
    decimals: 18,
    logoURI: 'https://cryptologos.cc/logos/weth-weth-logo.png'
  },
  {
    address: '0x1f9840a85d5af5bf1d1762f925bdaddc4201f984', // UNI on Ethereum
    name: 'Uniswap',
    symbol: 'UNI',
    decimals: 18,
    logoURI: 'https://cryptologos.cc/logos/uniswap-uni-logo.png'
  },
  {
    address: '0x6b175474e89094c44da98b954eedeac495271d0f', // DAI on Ethereum
    name: 'Dai',
    symbol: 'DAI',
    decimals: 18,
    logoURI: 'https://cryptologos.cc/logos/multi-collateral-dai-dai-logo.png'
  }
]

// This is now purely for fallback UI development and initial page load.
// The real data will be generated by the services.
export const MOCK_ARBITRAGE_OPPORTUNITIES: ArbitrageOpportunity[] = [
  {
    id: 'mock-1',
    token: POPULAR_TOKENS[1], // UNI
    buyDEX: {
      dex: SUPPORTED_DEXS[1], // SushiSwap
      token: POPULAR_TOKENS[1],
      price: 7.12,
      priceUSD: 7.12,
      liquidity: 15000000,
      volume24h: 2500000,
      lastUpdated: new Date()
    },
    sellDEX: {
      dex: SUPPORTED_DEXS[0], // Uniswap V2
      token: POPULAR_TOKENS[1],
      price: 7.15,
      priceUSD: 7.15,
      liquidity: 20000000,
      volume24h: 3000000,
      lastUpdated: new Date()
    },
    priceDifference: 0.03,
    priceDifferencePercent: 0.42,
    estimatedCosts: {
      buyGasFee: 15.5,
      sellGasFee: 12.1,
      bridgeFee: 0,
      tradingFees: 21.45,
      totalCosts: 49.05
    },
    netProfit: -5.2,
    netProfitPercent: -0.52,
    isCrossChain: false,
    riskLevel: 'high',
    lastUpdated: new Date()
  }
]

export const MOCK_GAS_PRICES: GasPrice[] = [
  {
    chain: 'ethereum',
    fast: 45,
    standard: 25,
    slow: 15,
    lastUpdated: new Date()
  },
  {
    chain: 'bsc',
    fast: 5,
    standard: 3,
    slow: 1,
    lastUpdated: new Date()
  },
  {
    chain: 'polygon',
    fast: 100,
    standard: 50,
    slow: 30,
    lastUpdated: new Date()
  }
]
